/** @type {import('tailwindcss').Config} */
export default {
    content: [
        "./index.html",
        "./src/**/*.{js,ts,jsx,tsx}",
    ],
    theme: {
        extend: {
            colors: {
                "primary-fixed": "#6ffbbe",
                "error-container": "#ffdad6",
                "surface-container": "#e5eeff",
                "inverse-surface": "#213145",
                "primary": "#006c49",
                "inverse-primary": "#4edea3",
                "on-tertiary-fixed-variant": "#842225",
                "surface-container-low": "#eff4ff",
                "error": "#ba1a1a",
                "on-primary-container": "#00422b",
                "on-tertiary-container": "#711419",
                "tertiary-fixed": "#ffdad7",
                "surface-container-highest": "#d3e4fe",
                "surface-variant": "#d3e4fe",
                "tertiary-container": "#fc7c78",
                "on-secondary": "#ffffff",
                "surface": "#f8f9ff",
                "surface-container-high": "#dce9ff",
                "surface-container-lowest": "#ffffff",
                "on-error": "#ffffff",
                "secondary-container": "#dae2fd",
                "on-secondary-fixed-variant": "#3f465c",
                "background": "#f8f9ff",
                "surface-tint": "#006c49",
                "on-tertiary-fixed": "#410005",
                "secondary": "#565e74",
                "surface-bright": "#f8f9ff",
                "on-secondary-container": "#5c647a",
                "on-background": "#0b1c30",
                "tertiary": "#a43a3a",
                "on-error-container": "#93000a",
                "primary-fixed-dim": "#4edea3",
                "on-primary-fixed-variant": "#005236",
                "on-primary-fixed": "#002113",
                "surface-dim": "#cbdbf5",
                "secondary-fixed-dim": "#bec6e0",
                "on-secondary-fixed": "#131b2e",
                "inverse-on-surface": "#eaf1ff",
                "secondary-fixed": "#dae2fd",
                "on-surface": "#0b1c30",
                "outline-variant": "#bbcabf",
                "tertiary-fixed-dim": "#ffb3af",
                "on-primary": "#ffffff",
                "primary-container": "#10b981",
                "on-surface-variant": "#3c4a42",
                "on-tertiary": "#ffffff",
                "outline": "#6c7a71"
            },
            fontFamily: {
                "headline": ["Inter", "sans-serif"],
                "body": ["Inter", "sans-serif"],
                "label": ["Inter", "sans-serif"]
            },
            borderRadius: {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "2xl": "1rem",
                "3xl": "1.5rem",
                "full": "9999px"
            },
        },
    },
    plugins: [],
}
